[package]
name = "gagaga"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { version = "1.0.70", features = ["backtrace"] }
axum = { version = "0.6.12", features = ["tracing"] } # tracing -- log rejected requests
chrono = "0.4.24"
http = "0.2.9"
image = { version = "0.24.6", default-features = false, features = ["jpeg", "png", "gif", "webp"] }
serde = { version = "1.0.159", features = ["derive"] }
serde_json = "1.0.95"
thiserror = "1.0.40"
tokio = { version = "1.27.0", features = ["full"] }
tower-http = { version = "0.4.0", features = ["trace"] } # tracing -- useful logging for axum
tracing = "0.1.37"
tracing-subscriber = "0.3.16"

[profile.release]
lto = "thin"
overflow-checks = true
